<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ProductVersionFile>$(MSBuildProjectDirectory)/../../VERSION</ProductVersionFile>
    <ProductVersion Condition="'$(ProductVersion)' == ''">$([System.IO.File]::ReadAllText('$(ProductVersionFile)').Trim())</ProductVersion>
    <Version>$(ProductVersion)</Version>
    <AssemblyVersion>$(ProductVersion).0</AssemblyVersion>
    <FileVersion>$(ProductVersion).0</FileVersion>
    <InformationalVersion>$(ProductVersion)</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>

    <ProductApplicationName Condition="'$(ProductApplicationName)' == ''">WebAssistant</ProductApplicationName>
    <ProductFileDescription Condition="'$(ProductFileDescription)' == ''">WebAssistant</ProductFileDescription>
    <ProductCompanyName Condition="'$(ProductCompanyName)' == ''">WebAssistant</ProductCompanyName>
    <ProductCopyright Condition="'$(ProductCopyright)' == ''">Copyright © WebAssistant</ProductCopyright>
    <Product>$(ProductApplicationName)</Product>
    <AssemblyTitle>$(ProductFileDescription)</AssemblyTitle>
    <Description>$(ProductFileDescription)</Description>
    <Company>$(ProductCompanyName)</Company>
    <Copyright>$(ProductCopyright)</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting.Systemd" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="10.0.11" />
    <PackageReference Include="WebAssistant.NAPS2.Sdk" Version="1.3.0-webassistant.3.450cba65" />
    <PackageReference Include="NAPS2.Images.Gdi" Version="1.3.0" />
    <PackageReference Include="NAPS2.Images.Gtk" Version="1.3.0" />
    <PackageReference Include="NAPS2.Sdk.Worker.Win32" Version="1.3.0" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="../../docs/scanner-settings.schema.json">
      <Link>scanner-settings.schema.json</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>WebAssistant.CoreTests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>
</Project>
