stages:
  - package

linux-package:
  stage: package
  script:
    - './build/linux/package.sh artifacts/linux-x64'
  artifacts:
    paths:
      - artifacts/linux-x64/
    expire_in: 7 days
  only:
    changes:
      - ".gitlab-ci.yml"
      - "README.md"
      - "WebAssistant.sln"
      - "NuGet.Config"
      - "src/**/*"
      - "build/**/*"
      - "install/**/*"
      - "docs/**/*"
      - "vendor/**/*"
